import os
import argparse
import torch
import numpy as np
from PIL import Image, ImageDraw
from diffusers import StableDiffusionInpaintPipeline
import cv2
from tqdm import tqdm


def parse_args():
    parser = argparse.ArgumentParser(
        description="Perform boundary inpainting on overlaid damage images and regenerate YOLO labels."
    )

    parser.add_argument(
        "--image_dir",
        type=str,
        required=True,
        help="Directory containing overlaid images generated by the overlay stage."
    )
    parser.add_argument(
        "--label_dir",
        type=str,
        required=True,
        help="Directory containing YOLO label files corresponding to the overlaid images."
    )
    parser.add_argument(
        "--save_dir",
        type=str,
        required=True,
        help="Output directory where the inpainted images will be saved. Visualization and debug mask folders will also be created inside this directory."
    )
    parser.add_argument(
        "--label_output_dir",
        type=str,
        required=True,
        help="Output directory where the updated YOLO label files for the inpainted images will be saved."
    )
    parser.add_argument(
        "--model_path",
        type=str,
        required=True,
        help="Path to the Stable Diffusion inpainting model directory."
    )
    parser.add_argument(
        "--lora_path",
        type=str,
        default=None,
        help="Optional path to LoRA attention processor weights."
    )
    parser.add_argument(
        "--prompt",
        type=str,
        default="car surface with damage",
        help="Text prompt used for boundary inpainting."
    )
    parser.add_argument(
        "--guidance_scale",
        type=float,
        default=8.0,
        help="Guidance scale used during inpainting."
    )
    parser.add_argument(
        "--strength",
        type=float,
        default=1.0,
        help="Strength value used during inpainting."
    )
    parser.add_argument(
        "--num_inference_steps",
        type=int,
        default=50,
        help="Number of diffusion inference steps."
    )
    parser.add_argument(
        "--border_ratio",
        type=float,
        default=0.1,
        help="Ratio used to shrink the inner bounding box relative to the original box."
    )
    parser.add_argument(
        "--expand_ratio",
        type=float,
        default=0.05,
        help="Ratio used to expand the outer mask area around the original box."
    )

    return parser.parse_args()


def create_border_mask_from_yolo(label_path, image_size, border_ratio=0.1, expand_ratio=0.1):
    W, H = image_size
    mask = Image.new("L", (W, H), 0)
    draw = ImageDraw.Draw(mask)
    inner_box = None

    try:
        with open(label_path, "r", encoding="utf-8") as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) != 5:
                    continue

                cls, x, y, w, h = map(float, parts)
                cx, cy = x * W, y * H
                box_w, box_h = w * W, h * H

                ex_w, ex_h = box_w * (1 + 2 * expand_ratio), box_h * (1 + 2 * expand_ratio)
                in_w, in_h = box_w * (1 - 2 * border_ratio), box_h * (1 - 2 * border_ratio)

                ex1, ey1 = cx - ex_w / 2, cy - ex_h / 2
                ex2, ey2 = cx + ex_w / 2, cy + ex_h / 2
                ix1, iy1 = cx - in_w / 2, cy - in_h / 2
                ix2, iy2 = cx + in_w / 2, cy + in_h / 2

                draw.rectangle([ex1, ey1, ex2, ey2], fill=255)
                draw.rectangle([ix1, iy1, ix2, iy2], fill=0)

                inner_box = (cls, ix1, iy1, ix2, iy2)
                break

    except Exception as e:
        print(f"Warning: failed to create mask from {label_path} -> {e}")

    return mask, inner_box


def load_pipeline(model_path, lora_path=None):
    device = "cuda" if torch.cuda.is_available() else "cpu"

    pipe = StableDiffusionInpaintPipeline.from_pretrained(
        model_path,
        torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
    ).to(device)

    pipe.safety_checker = lambda images, **kwargs: (images, [False] * len(images))
    pipe.enable_attention_slicing()

    if lora_path:
        pipe.unet.load_attn_procs(lora_path)

    return pipe


def inpaint_and_save_sd(
    pipe,
    image_path,
    label_path,
    out_path,
    visual_path,
    mask_debug_path,
    label_out_path,
    prompt="car surface with damage",
    guidance_scale=8.0,
    strength=1.0,
    num_inference_steps=50,
    border_ratio=0.03,
    expand_ratio=0.17
):
    orig = Image.open(image_path).convert("RGB")
    W, H = orig.size

    mask, inner_box = create_border_mask_from_yolo(
        label_path,
        (W, H),
        border_ratio=border_ratio,
        expand_ratio=expand_ratio
    )

    if mask is None or inner_box is None or np.array(mask).sum() == 0:
        print(f"Skipping due to invalid mask: {label_path}")
        return False

    if mask_debug_path:
        mask.save(mask_debug_path)

    result = pipe(
        prompt=prompt,
        image=orig,
        mask_image=mask,
        guidance_scale=guidance_scale,
        strength=strength,
        num_inference_steps=num_inference_steps
    ).images[0]

    result.save(out_path, format="JPEG", quality=100, subsampling=0, optimize=True)

    res_W, res_H = result.size
    scale_x = res_W / W
    scale_y = res_H / H

    cls, ix1, iy1, ix2, iy2 = inner_box
    ix1 *= scale_x
    ix2 *= scale_x
    iy1 *= scale_y
    iy2 *= scale_y

    x_center = (ix1 + ix2) / 2
    y_center = (iy1 + iy2) / 2
    box_w = ix2 - ix1
    box_h = iy2 - iy1

    with open(label_out_path, "w", encoding="utf-8") as f:
        f.write(
            f"{int(cls)} "
            f"{x_center / res_W:.6f} "
            f"{y_center / res_H:.6f} "
            f"{box_w / res_W:.6f} "
            f"{box_h / res_H:.6f}\n"
        )

    vis = np.array(result)[:, :, ::-1].copy()
    cv2.rectangle(vis, (int(ix1), int(iy1)), (int(ix2), int(iy2)), (0, 255, 0), 2)
    cv2.putText(
        vis,
        "inner-box",
        (int(ix1), max(int(iy1) - 10, 20)),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.6,
        (0, 255, 0),
        2
    )
    cv2.imwrite(visual_path, vis, [cv2.IMWRITE_JPEG_QUALITY, 100])

    return True


def main():
    args = parse_args()

    image_dir = args.image_dir
    label_dir = args.label_dir
    save_dir = args.save_dir
    label_output_dir = args.label_output_dir

    visual_dir = os.path.join(save_dir, "visual")
    debug_mask_dir = os.path.join(save_dir, "debug_masks")

    os.makedirs(save_dir, exist_ok=True)
    os.makedirs(visual_dir, exist_ok=True)
    os.makedirs(debug_mask_dir, exist_ok=True)
    os.makedirs(label_output_dir, exist_ok=True)

    pipe = load_pipeline(args.model_path, args.lora_path)

    for fname in tqdm(os.listdir(image_dir), desc="Boundary inpainting"):
        if not fname.lower().endswith((".jpg", ".jpeg", ".png")):
            continue

        base = os.path.splitext(fname)[0]

        save_path = os.path.join(save_dir, f"{base}_inpaint.jpg")
        label_out_path = os.path.join(label_output_dir, f"{base}_inpaint.txt")

        if os.path.exists(save_path) and os.path.exists(label_out_path):
            print(f"Skipping already processed file: {base}")
            continue

        img_path = os.path.join(image_dir, fname)
        label_path = os.path.join(label_dir, base + ".txt")

        if not os.path.exists(label_path) or os.path.getsize(label_path) == 0:
            continue

        vis_path = os.path.join(visual_dir, f"{base}_visual.jpg")
        mask_path = os.path.join(debug_mask_dir, f"{base}_mask.png")

        try:
            success = inpaint_and_save_sd(
                pipe=pipe,
                image_path=img_path,
                label_path=label_path,
                out_path=save_path,
                visual_path=vis_path,
                mask_debug_path=mask_path,
                label_out_path=label_out_path,
                prompt=args.prompt,
                guidance_scale=args.guidance_scale,
                strength=args.strength,
                num_inference_steps=args.num_inference_steps,
                border_ratio=args.border_ratio,
                expand_ratio=args.expand_ratio
            )

            if success:
                print(f"Done: {base}")

        except Exception as e:
            print(f"Error processing {base} -> {e}")


if __name__ == "__main__":
    main()